### ISSUE TITLE
Error: Caused by: dev.rollczi.litecommands.injector.MissingBindException: Have you added type bind or contextual bind? CometCommand#find(Player sender) [org.bukkit.entity.Player]

### ISSUE THREAD

**Issue by BlackBaroness** [Rollczi/LiteCommands#204]
Full stacktrace:

```java
[20:28:26 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'comet find' in dev.rollczi.litecommands.bukkit.SimpleCommand(comet)
        at org.bukkit.command.SimpleCommandMap.dispatch(:162) ~[guardspigot.jar:git-Paper-8359863]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(:687) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(:1504) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(:1309) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(:45) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(:5) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(:14) ~[guardspigot.jar:git-Paper-8359863]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(:46) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(:854) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(:431) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(:778) ~[guardspigot.jar:git-Paper-8359863]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(:669) ~[guardspigot.jar:git-Paper-8359863]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: dev.rollczi.litecommands.injector.MissingBindException: Have you added type bind or contextual bind? CometCommand#find(Player sender) [org.bukkit.entity.Player]
        at dev.rollczi.litecommands.implementation.injector.CommandInjector.invokeExecutable(CommandInjector.java:177) ~[?:?]
        at dev.rollczi.litecommands.implementation.injector.CommandInjector.invokeExecutables(CommandInjector.java:100) ~[?:?]
        at dev.rollczi.litecommands.implementation.injector.CommandInjector.invokeMethod(CommandInjector.java:81) ~[?:?]
        at dev.rollczi.litecommands.implementation.MethodExecutor.execute(MethodExecutor.java:26) ~[?:?]
        at dev.rollczi.litecommands.implementation.LiteArgumentArgumentExecutor.execute(LiteArgumentArgumentExecutor.java:65) ~[?:?]
        at dev.rollczi.litecommands.implementation.LiteCommandSection.execute(LiteCommandSection.java:89) ~[?:?]
        at dev.rollczi.litecommands.command.CommandService.lambda$register$0(CommandService.java:42) ~[?:?]
        at dev.rollczi.litecommands.bukkit.SimpleCommand.execute(SimpleCommand.java:29) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(:152) ~[guardspigot.jar:git-Paper-8359863]
        ... 14 more
```

My code:

```java
private void registerCommands() {
    LiteBukkitFactory.builder(server, "ElementComets")
        .commandInstance(cometCommand)
        .register();
}
```

```java
@Route(name = "comet")
@Permission("comets.admin")
@RequiredArgsConstructor(onConstructor_ = @Inject)
public class CometCommand {

   // ...

    @Execute(route = "find")
    public void find(Player sender) {
        // ...
    }

}
```

I run `Java 17`, `PaperSpigot 1.12.2` and `LiteCommands 2.8.6`. I use `bukkit` module.

**Comment by Rollczi** [comment]
In Minecraft, the sender is not always a type of `Player`. It is necessary to handle this case by registering a contextual bind that is based on the command invocation context for the `Player`. You can use the ready-made implementation `BukkitOnlyPlayerContextual`.
```java
.contextualBind(Player.class, new BukkitOnlyPlayerContextual<>("&cThis command is only for players!"))
```
