### ISSUE TITLE
java.lang.IllegalArgumentException: Max cannot be less than min [Programmatic]

### ISSUE THREAD

**Issue by Rollczi** [Rollczi/LiteCommands#379]
```java
[18:45:52 ERROR]: java.lang.IllegalArgumentException: Max cannot be less than min
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.range.Range.<init>(Range.java:13)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.range.Range.range(Range.java:53)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.join.JoinArgumentResolver.getTypedRange(JoinArgumentResolver.java:42)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.join.JoinArgumentResolver.getTypedRange(JoinArgumentResolver.java:14)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.argument.parser.TypedParser.getRange(TypedParser.java:26)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.argument.parser.TypedParser.getRange(TypedParser.java:8)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.input.raw.RawInputAnalyzer$Context.<init>(RawInputAnalyzer.java:85)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.input.raw.RawInputAnalyzer.toContext(RawInputAnalyzer.java:43)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.argument.parser.input.RawParseableInput$RawInputMatcher.nextArgument(RawParseableInput.java:45)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.ScheduledRequirementResolver.matchArgument(ScheduledRequirementResolver.java:76)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.ScheduledRequirementResolver.lambda$prepareRequirements$0(ScheduledRequirementResolver.java:48)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.scheduler.SchedulerSameThreadImpl.supplyLater(SchedulerSameThreadImpl.java:16)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.scheduler.Scheduler.supply(Scheduler.java:52)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.ScheduledRequirementResolver.lambda$toScheduled$3(ScheduledRequirementResolver.java:63)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.ScheduledRequirement.runMatch(ScheduledRequirement.java:25)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.CommandExecuteService.match(CommandExecuteService.java:237)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.CommandExecuteService.match(CommandExecuteService.java:209)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:152)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.CommandExecuteService.execute0(CommandExecuteService.java:122)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.executor.CommandExecuteService.execute(CommandExecuteService.java:62)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.command.CommandManager$PlatformListener.execute(CommandManager.java:63)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.velocity.VelocityCommand.execute(VelocityCommand.java:55)
[18:45:52 ERROR]: 	at dev.rollczi.litecommands.velocity.VelocityCommand.execute(VelocityCommand.java:20)
```
```java
        this
            .context("sender", Audience.class)
            .argumentJoin("message");
```

**Comment by Rollczi** [comment]
Solution: replace -1 with max int value
![image](https://github.com/Rollczi/LiteCommands/assets/49173834/a2ca6ac3-e710-4cf9-993a-baada0c4b322)
