### ISSUE TITLE
IOOBE in Suggestion

### ISSUE THREAD

**Issue by SfenKer** [Rollczi/LiteCommands#417]
Module: `litecommands-jda`
Version: `3.4.3`
```
[09:04:02] [ERROR] [net.dv8tion.jda.api.JDA             ]: One of the EventListeners had an uncaught exception
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at dev.rollczi.litecommands.suggestion.Suggestion.of(Suggestion.java:111)
        at dev.rollczi.litecommands.jda.JDASuggestionInput$JDASuggestionMatcher.nextArgument(JDASuggestionInput.java:53)
        at dev.rollczi.litecommands.suggestion.SuggestionService.suggestArgument(SuggestionService.java:146)
        at dev.rollczi.litecommands.suggestion.SuggestionService.suggestExecutor(SuggestionService.java:123)
        at dev.rollczi.litecommands.suggestion.SuggestionService.suggest0(SuggestionService.java:61)
        at dev.rollczi.litecommands.suggestion.SuggestionService.suggest(SuggestionService.java:34)
        at dev.rollczi.litecommands.command.CommandManager$PlatformListener.suggest(CommandManager.java:71)
        at dev.rollczi.litecommands.jda.JDAPlatform$SlashCommandController.onCommandAutoCompleteInteraction(JDAPlatform.java:114)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:456)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:98)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:169)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:89)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by SfenKer** [comment]
commands reference:
[pl/mrstudios/essential/command](https://github.com/MrStudios/rust-essential/tree/ver/latest/src/main/java/pl/mrstudios/essential/command)
[pl/mrstudios/essential/module/calculator/command](https://github.com/MrStudios/rust-essential/tree/ver/latest/src/main/java/pl/mrstudios/essential/module/calculator/command)

**Comment by Rollczi** [comment]
#419
