### ISSUE TITLE
IncompatibleClassChangeError when parsing a custom argument

### ISSUE THREAD

**Issue by BlackBaroness** [Rollczi/LiteCommands#473]
My code:

```java
@RequiredArgsConstructor
public class LuckyBlockConfigurationArgument extends ArgumentResolver<CommandSender, PluginConfiguration.LuckyBlockConfiguration> {

    private final ClashLuckyBlocksPlugin plugin;

    @Override
    protected ParseResult<PluginConfiguration.LuckyBlockConfiguration> parse(Invocation<CommandSender> invocation, Argument<PluginConfiguration.LuckyBlockConfiguration> argument, String input) {
        return plugin.configuration().findLuckyBlock(input)
            .map(ParseResult::success)
            .orElseGet(() -> ParseResult.failure(MiniMessage.miniMessage().deserialize(
                plugin.messages().unknownLuckyBlock(),
                Placeholder.unparsed("id", input)
            )));
    }

    @Override
    public SuggestionResult suggest(Invocation<CommandSender> invocation, Argument<PluginConfiguration.LuckyBlockConfiguration> argument, SuggestionContext context) {
        return SuggestionResult.of(plugin.configuration().luckyblocks().keySet());
    }
}
```

Error:
```
[07:58:16 WARN]: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class dev/rollczi/litecommands/argument/parser/ParseResult. Method 'dev.rollczi.litecommands.argument.parser.ParseResult success(java.lang.Object)' at index 50 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[07:58:16 WARN]:        at ClashLuckyBlocks.jar//eu.miopowered.clashluckyblocks.plugin.command.argument.LuckyBlockConfigurationArgument.parse(LuckyBlockConfigurationArgument.java:23)
[07:58:16 WARN]:        at ClashLibrary.jar//dev.rollczi.litecommands.argument.resolver.ArgumentResolver.parse(ArgumentResolver.java:19)
```

If I avoid using Optional and use nulls + if/else, the issue still persists. Some of our plugins were fixed by specifying an exact type (`ParseResult<ARG>`) when running `Optional#map`, because Java threats it like `ParseCompletedResult` or something... That's a strange issue, I am not sure why is it happening.

**Comment by Rollczi** [comment]
First of all, relocate LiteCommands in your plugin. You error is related to class loading from other plugin. If you don't want to relocate LiteCommands then update all versions of the framework in your plugins.
